apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-indexer
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: crawler-indexer
            image: "{{ .Values.crawlerIndexer.repository }}:{{ .Values.crawlerIndexer.tag }}"
            env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_HOST 
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_PORT 
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_USERNAME 
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_NAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_PASSWORD
          restartPolicy: OnFailure
