apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: search-engine
  name: postgres
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels: 
        app: postgres
    spec: 
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env: 
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-sec
                key: DB_NAME
        volumeMounts:
          - name: postgres-volume
            mountPath: /var/lib/postgresql/data
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - "$(POSTGRES_USER)"
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
      volumes: 
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-volume-claim
