apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: search-engine
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres
