apiVersion: v1
kind: Secret
metadata: 
  namespace: search-engine
  name: postgres-sec
type: Opaque
data:  
  DB_HOST: cG9zdGdyZXMtc3Zj        # postgres-svc (base64)
  DB_PORT: NTQzMg==                # 5432 (base64)
  DB_USERNAME: YWRtaW4=            # admin (base64)
  DB_PASSWORD: cGFzc3dvcmQxMjM=    # password123 (base64)
  DB_NAME: c2VhcmNoX2VuZ2luZQ==    # search_engine (base64)
