apiVersion: v1
kind: Service
metadata:
  namespace: search-engine
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
