FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && pip install -r requirements.txt

# Tải supercronic để chạy cron
ADD https://github.com/aptible/supercronic/releases/download/v0.2.4/supercronic-linux-amd64 /usr/local/bin/supercronic
RUN chmod +x /usr/local/bin/supercronic

COPY crontab /app/crontab

CMD ["supercronic", "/app/crontab"]
