apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
  namespace: search-engine
  labels:
    app: search-api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
        - name: search-api
          image: andrenguyen03/search-api:11
          ports:
            - containerPort: 8000
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: DB_HOST
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: DB_PORT
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: DB_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: DB_PASSWORD
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-sec
                  key: DB_NAME
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 30
