apiVersion: v1
kind: Service
metadata:
  name: search-api
  namespace: search-engine
spec:
  selector:
    app: search-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP