apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
      - name: search-api
        image: "{{ .Values.searchApi.repository }}:{{ .Values.searchApi.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: DB_HOST
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: DB_PORT
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: DB_USERNAME
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: DB_NAME
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: DB_PASSWORD
